import java.awt.CardLayout;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;

/*
 * Login.java
 *
 * Created on __DATE__, __TIME__
 */

/**
 *
 * @author  __USER__
 */
public class Login extends javax.swing.JPanel {

	/** Creates new form Login */
	public Login() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		jLabel3 = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jPasswordField1 = new javax.swing.JPasswordField();
		jLabel5 = new javax.swing.JLabel();
		jLabel6 = new javax.swing.JLabel();

		setBackground(new java.awt.Color(255, 255, 255));

		jButton1.setText("Browse");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Upload");
		jButton2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton2ActionPerformed(evt);
			}
		});

		jLabel1.setBackground(new java.awt.Color(204, 0, 51));
		jLabel1.setFont(new java.awt.Font("Georgia", 1, 22));
		jLabel1.setForeground(new java.awt.Color(204, 51, 0));
		jLabel1.setText("WELCOME");

		jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12));
		jLabel3.setText("Image Name");

		jLabel4.setFont(new java.awt.Font("Georgia", 1, 14));
		jLabel4.setText("Enter your Password :-");

		jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18));
		jPasswordField1.setText("jPasswordField1");
		jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jPasswordField1ActionPerformed(evt);
			}
		});

		jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 22));
		jLabel6.setForeground(new java.awt.Color(0, 0, 255));

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(78, 78, 78)
										.addComponent(
												jLabel1,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												139, Short.MAX_VALUE)
										.addGap(18, 18, 18)
										.addComponent(
												jLabel6,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												242,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(166, 166, 166))
						.addGroup(
								layout.createSequentialGroup().addGap(369, 369,
										369).addComponent(jLabel5,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										250,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap())
						.addGroup(
								layout
										.createSequentialGroup()
										.addGap(54, 54, 54)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																263,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel4)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jLabel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				423,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jButton2)
																						.addComponent(
																								jButton1)
																						.addComponent(
																								jLabel3,
																								javax.swing.GroupLayout.Alignment.TRAILING))))
										.addGap(77, 77, 77)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel1)
														.addComponent(
																jLabel6,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																24,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(10, 10, 10)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel3)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jButton2))
														.addComponent(
																jLabel2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																386,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jLabel4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												25,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel5)
														.addComponent(
																jPasswordField1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));
	}// </editor-fold>
	//GEN-END:initComponents

	private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	String name, path;
	File f;

	public boolean checkpassword() {
		String s = "", s2 = "";
		String password = jPasswordField1.getText();
		try {
			BufferedReader br = new BufferedReader(new FileReader(
					"C://Users//Public//notebook//" + "password.txt"));

			while ((s2 = br.readLine()) != null) {
				s = s2;
			}
			br.close();
		} catch (Exception e) {
			// TODO: handle exception
		}
		if (s.equals(password)) {
			return true;
		} else {
			jLabel5.setText("Please Enter correct password..!!!");
			return false;
		}

	}

	public void display() {

		try {
			FileInputStream fi = new FileInputStream(path);
			FileOutputStream fout = new FileOutputStream(
					"C://Users//Public//notebook//" + "profile.jpg");
			int j;
			while ((j = fi.read()) != -1) {
				fout.write(j);

			}
		} catch (Exception e) {
			// TODO: handle exception
		}
	}
	
	public void setname()
	{
		String s = "", s2 = "";
		try {
			BufferedReader br = new BufferedReader(new FileReader(
					"C://Users//Public//notebook//" + "name.txt"));
			while ((s2 = br.readLine()) != null) {
				s = s2;
			}
			br.close();
		} catch (Exception e) {
			// TODO: handle exception
		}
		jLabel6.setText(s);
	}

	public void show() {

		setname();
		ImageIcon image;
		File file = new File("C://Users//Public//notebook//" + "profile.jpg");
		if (file.exists()) {
			image = new ImageIcon("C://Users//Public//notebook//"
					+ "profile.jpg");
		} else {
			image = new ImageIcon(getClass().getResource("/imgs/profile.jpg"));
		}
		jLabel2.setIcon(image);
	}

	private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
		try {
			BufferedImage bi = ImageIO.read(f);

		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
		ImageIcon image;
		image = new ImageIcon("C://Users//Public//notebook//" + "profile.jpg");

		jLabel2.setIcon(image);

		jLabel2.setLayout(new CardLayout());
	}

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
		JFileChooser fc = new JFileChooser();
		int i = fc.showOpenDialog(this);
		if (i == JFileChooser.APPROVE_OPTION) {
			f = fc.getSelectedFile();
			name = f.getName();
			path = f.getPath();
			display();
			jLabel3.setText(name);
		}
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton2;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JPasswordField jPasswordField1;
	// End of variables declaration//GEN-END:variables

}